### ISSUE TITLE
Slight problem

### ISSUE THREAD

**Issue by MikeDB1** [PitterL/cupdi#1]
I compiled this in Visual Studio 2017 and it works using a CH340 USB to serial convertor .... but only every other time :-(

On first, third, etc times I get "NVM initialise failed".

I've had a quick look at the code but can't see anything obvious as to why it fails exactly 50% of the time, although presumably this is because the failure puts the ATTINY414 in the correct state to be reprogrammed the next time.

Any thoughts or help most appreciated.

**Comment by mraardvark** [comment]
I have not used the c utility (I use pyupdi) but the symptom sounds like the double break recovery is not quite right.
You see, UPDI needs a slight nudge to wake it up (negative edge), but if its awake already, then the nudge is seen as a start-bit, which results in a framing error, which needs a double-break to recover from.
Omitting that nudge and going straight ahead with a SYNC will result in the opposite problem in case its not awake, and a similar recovery is required.
Not offering a fix, just a hint at what could be going wrong.

**Comment by MikeDB1** [comment]
Ah thanks - that sounds very plausible.  Does pyupdi not have the same problem in which case I'll look in there to see if they have a fix for this.

**Comment by MikeDB1** [comment]
Ah - just realised you're the person who wrote pyupdi.  I had to try the c version as the Python one wouldn't run on my PC - serial not found errors.

**Comment by mraardvark** [comment]
pyupdi _should_ work just fine (and if not it _should_ be fixed), so give it a try again perhaps.
If you are using Linux, remember you need to tweak the permissions of your serial port.

**Comment by MikeDB1** [comment]
Never used Python before but it gave this.  

Traceback (most recent call last):
  File "C:\Users\Mike\Downloads\pyupdi-master\pyupdi-master\pyupdi.py", line 11, in <module>
    from updi.nvm import UpdiNvmProgrammer
  File "C:\Users\Mike\Downloads\pyupdi-master\pyupdi-master\updi\nvm.py", line 6, in <module>
    from updi.application import UpdiApplication
  File "C:\Users\Mike\Downloads\pyupdi-master\pyupdi-master\updi\application.py", line 7, in <module>
    from updi.link import UpdiDatalink
  File "C:\Users\Mike\Downloads\pyupdi-master\pyupdi-master\updi\link.py", line 6, in <module>
    from updi.physical import UpdiPhysical
  File "C:\Users\Mike\Downloads\pyupdi-master\pyupdi-master\updi\physical.py", line 6, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'

**Comment by mraardvark** [comment]
Without going into detail, this should help:
`pip install pyserial` 
Then start to learn python ;)

**Comment by MikeDB1** [comment]
I'm a pure C++ person - anything else other than HTML/Javascript are things I'd never actually program in if I can avoid it :-)

**Comment by PitterL** [comment]
Nice to see you, Mraardvark.

Hi, Mike:
  I‘m not suggest use CH340 for UPDI communication. You could see the datasheet: 
https://cdn.sparkfun.com/datasheets/Dev/Arduino/Other/CH340DS1.PDF

It could not support 1.5 stop bit,  not matches UPDI protocol.

The most USB/Serial part i suggested use for the UPDI are these below:

SiliconLab CP210x (be carefull don't use pirate copy part)

Or use MCU type like ATMEL SAML21/D21:
https://www.microchip.com/Developmenttools/ProductDetails/ATSAMD21-XPRO
https://www.microchipdirect.com/product/search/all/ATSAMD21-XPRO

Any question could message me by Wechart: 126676275
or Mail to pitter.liao@microchip.com
